name: Deploy to EC2

on:
  push:
    branches:
      - dev  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change the Java version if needed
          distribution: 'adopt' # Specify the distribution for Java 11
        
      - name: Build with Maven
        run: mvn clean package
