name: Deploy to EC2

on:
  push:
    branches:
      - dev  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use Java 11 as specified in your pom.xml
          distribution: 'adopt'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          maven-version: '3.8.4'  # Specify the version of Maven as needed
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package
