name: Deploy to EC2

on:
  push:
    branches:
      - dev  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-spring-app .

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop my-spring-app || true
            docker rm my-spring-app || true
            docker rmi my-spring-app || true
            docker pull my-spring-app:latest
            docker run -d -p 8080:8080 --name my-spring-app my-spring-app:latest
